### PR TITLE
Fix: LiteralParser __contains__ method compares value of item with Literal arguments

### LINKED ISSUE #67: [BUG] Incomplete Support for Union or | Type Deserialization in Common Python Types (e.g., `int`, `Enum`, `Literal`)
* Dataclass Wizard version: 0.22.1
* Python version: 3.10.4
* Operating System: Ubuntu 22.04

### Description

Using the dataclass-wizard to deserialize a YAML file fails when trying to use string literals as field options.
In my particular case, a value in the config can be set manually or derived automatically depending on user preference.
In this instance, the only valid string value for `x` should be `Auto`. Any other value should fail to deserialize. However, since it appears that the parser is unaware of the possible equality of str/num/bytes to a Literal this fails.

### What I Did

```python
>>> from dataclass_wizard import YAMLWizard
>>> from typing import Literal
>>> from dataclasses import dataclass
>>> @dataclass
... class Example(YAMLWizard):
...     x: Literal["Auto"] | float
... 
>>> config_file = """
... x: Auto
... """
>>> Example.from_yaml(config_file)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "~/.venv/lib/python3.10/site-packages/dataclass_wizard/wizard_mixins.py", line 136, in from_yaml
    return fromdict(cls, o) if isinstance(o, dict) else fromlist(cls, o)
  File "~/.venv/lib/python3.10/site-packages/dataclass_wizard/loaders.py", line 536, in fromdict
    return load(d)
  File "~/.venv/lib/python3.10/site-packages/dataclass_wizard/loaders.py", line 619, in cls_fromdict
    cls_kwargs[field_name] = field_to_parser[field_name](
  File "~/.venv/lib/python3.10/site-packages/dataclass_wizard/parsers.py", line 250, in __call__
    raise ParseError(
dataclass_wizard.errors.ParseError: Failure parsing field `x` in class `Example`. Expected a type [typing.Literal['Auto'], <class 'float'>], got str.
  value: 'Auto'
  error: Object was not in any of Union types
  tag_key: '__tag__'
  json_object: '{"x": "Auto"}'
```

### PR DESCRIPTION
**Pull request by mikeweltevrede**
Closes #67.

Instead of checking that `type(item)` is `self.base_type` (like is implemented in the base class `AbstractParser`), we need to check if the `item` is in the values of the given `Literal`.

### CODE REVIEW

**Comment by rmmr** [comment]
Would be nice to see this fix merged :)

**Comment by mikeweltevrede** [comment]
@rmmr I was planning to post a reminder today, great minds think alike :')

**Comment by mikeweltevrede** [comment]
@rnag Would you have time to look at this PR? Thanks!

**Comment by mikeweltevrede** [comment]
@rnag Hello :) Have you been able to consider this? Thanks :)

**Comment by rnag** [comment]
@mikeweltevrede Thanks again for your work on this PR!

Sorry I have not had a chance to check it out until now. It seems a simple enough ask/fix, so I will go ahead and merge it.

Tests are failing due to Python compatibility, actually I am planning to drop support for Python earlier than 3.9 (3.6, 3.7, 3.8) shortly as they reached EOL already, so it's a sort of red herring here. I'll fix tests for now, and create a release w/ the changes shortly.

Thanks again for the fix on `LiteralParser`! It's much appreciated.

**Comment by rnag** [comment]
@mikeweltevrede  I was incorrect in that this would fix #67. It does not, but I'll post my observations in that issue.

**Pull request merged**
