### PR TITLE
DataClassWizard after upgrading to python3.11 is not working as expected

### PR DESCRIPTION
**Pull request by alexanderilyin**

### CODE REVIEW

**Comment by intentionally-left-nil** [comment]
This is an important fix, can we get it looked at @rnag ?

**Comment by SebastianBr** [comment]
I would also be interested in this fix @rnag Its simple and important. Otherwise this lib is dead for py3.11

**Comment by rnag** [comment]
LGTM @alexanderilyin, though I notice one test case is failing in Python 3.12 on my machine. I've implemented a fix, but I have to do some testing. I'll look into it tomorrow if time allows. Will go ahead and merge for now.

Thanks again for opening this PR and adding the changes - certainly saved me some time to find compatibillity errors 😅 . Will push merged changes from this and #104 as a patch version if I am able to tomorrow. I'm eager to extend support to PY 3.11 and 3.12 as well. Cheers!

**Comment by rnag** [comment]
@alexanderilyin This should be fixed as of `v0.22.3`. Please pull latest version of lib and test with py3.11+ and let me know.

Also I credited your contribution in [the changelog](
https://dataclass-wizard.readthedocs.io/en/latest/history.html#id1), hope you don't mind 🙂.

**Comment by alexanderilyin** [comment]
image

**Pull request merged**
